#!/bin/sh

UNDOTTED="./undotted"

files=(
"$HOME/.vimrc"
"$HOME/.tmux.conf"
"$HOME/.extend.vim"
"$HOME/.config/nvim/static/neovim.cat"
"$HOME/.config/nvim/init.lua"
"$HOME/.config/nvim/lua/v/basic.lua"
"$HOME/.config/nvim/lua/v/conf_dashboard.lua"
"$HOME/.config/nvim/lua/v/packages.lua"
"$HOME/.config/nvim/lua/v/preferences.lua"
"$HOME/.config/nvim/lua/v/keymaps.lua"
"$HOME/.config/nvim/lua/v/my_lsp.lua"
"$HOME/.vim/coc-settings.json"
"$HOME/.config/nvim/coc-settings.json"
"$HOME/.zshrc"
"$HOME/.gitconfig"
"$HOME/.config/kitty/kitty.conf"
# "$HOME/.config/kitty/Batman.conf"
"$HOME/.config/alacritty/alacritty.yml"
"$HOME/.tmux.conf.local"
)
repo_files=(
"$UNDOTTED/vimrc"
"$UNDOTTED/tmux.conf"
"$UNDOTTED/extend.vim"
"$UNDOTTED/nvim/static/neovim.cat"
"$UNDOTTED/init.lua"
"$UNDOTTED/nvim/lua/basic.lua"
"$UNDOTTED/nvim/lua/conf_dashboard.lua"
"$UNDOTTED/nvim/lua/packages.lua"
"$UNDOTTED/nvim/lua/preferences.lua"
"$UNDOTTED/nvim/lua/keymaps.lua"
"$UNDOTTED/nvim/lua/my_lsp.lua"
"$UNDOTTED/coc-settings.vim8.json"
"$UNDOTTED/coc-settings.json"
"$UNDOTTED/zshrc"
"$UNDOTTED/gitconfig"
"$UNDOTTED/kitty.conf"
# "$UNDOTTED/Batman.conf"
"$UNDOTTED/alacritty.yml"
"$UNDOTTED/tmux.conf.local"
)
