#!/bin/sh
current_dir="$(dirname "$0")"
source "$current_dir/data.sh"

# Read config files from repo
files=("$HOME/.vimrc" "$HOME/.config/nvim/init.vim" "$HOME/.zshrc")
repo_files=("./vim/.vimrc" "./vim/init.vim" "./zsh/.zshrc" )
for (( i = 0; i < ${#files[@]}; ++i )); do
    cat "${repo_files[i]}" > "${files[i]}"
    echo "${repo_files[i]} to ${files[i]}"
done
