#!/bin/sh
current_dir="$(dirname "$0")"
source "$current_dir/data.sh"

function dotfiles_destroyer() {
 # Read config files from repo
 #for (( i = 0; i < ${#files[@]}; ++i )); do
     #ln -f "${repo_files[i]}" "${files[i]}"
     #echo "Writes ${repo_files[i]} to ${files[i]}"
 #done
for config in "${!configs[@]}"; do
  #machine_source="${configs[$config][0]}"
  ln -f "${configs[0]}" "${configs[1]}"
  echo "Writes ${repo_files[i]} to ${files[i]}"
done
}

function really_sure() {
 read -p "Like, really sure? [Y/n] " yn
 case $yn in
     [Yy]) echo "Okay then!"; dotfiles_destroyer; break;;
     [Nn]) exit;;
     *) echo "Only YES or NO!"; really_sure;;
 esac
}

function sure() {
 read -p "Are you sure? [Y/n] " yn
 case $yn in
     [Yy]) really_sure; break;;
     [Nn]) exit;;
     *) echo "Only YES or NO!"; sure;;
 esac
}

function main() {
 read -p "Do you wish override the machine's dotfiles? [Y/n] " yn
 case $yn in
     [Yy]) sure; break;;
     [Nn]) exit;;
     *) echo "Only YES or NO!"; main;;
 esac
}

main


