#!/bin/sh
current_dir="$(dirname "$0")"
source "$current_dir/data.sh"

function dotfiles_destroyer() {
 # Read config files from repo
 for (( i = 0; i < ${#files[@]}; ++i )); do
     cat "${repo_files[i]}" > "${files[i]}"
     echo "${repo_files[i]} to ${files[i]}"
 done
}


read -p "Do you wish override the machines dotfiles?" yn
case $yn in
    [Yy]* ) make install; break;;
    [Nn]* ) exit;;
esac

