#!/bin/sh

VIMRC=$HOME/.vimrc
NVIMRC=$HOME/.config/nvim/init.vim
ZSHRC=$HOME/.zshrc

# update edited file in used to this repo
cat $VIMRC > ./vim/.vimrc
cat $ZSHRC > ./zsh/.zshrc
cat $NVIMRC > ./vim/init.vim
